name: b
description: Your best personal accountant.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  lottie: ^1.4.3
  responsive_sizer: ^3.1.1
  font_awesome_flutter: ^10.2.1
  intl: ^0.17.0
  syncfusion_flutter_charts: ^20.3.47

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.1
  hive_generator: ^1.1.3

flutter:
  uses-material-design: true
  assets:
    - assets/

  
  
  
  
  
  
  
  
  
  
